language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t klimandrew/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true klimandrew/react-test yarn test

after_success:
  - docker build -t klimandrew/multi-client ./client
  - docker build -t klimandrew/multi-nginx ./nginx
  - docker build -t klimandrew/multi-server ./server
  - docker build -t klimandrew/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push klimandrew/multi-client
  - docker push klimandrew/multi-nginx
  - docker push klimandrew/multi-server
  - docker push klimandrew/multi-worker
