language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t klimandrew/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true klimandrew/react-test yarn test

after_success:
  - docker build -t klimandrew/multi-client ./client
  - docker build -t klimandrew/multi-nginx ./nginx
  - docker build -t klimandrew/multi-server ./server
  - docker build -t klimandrew/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push klimandrew/multi-client
  - docker push klimandrew/multi-nginx
  - docker push klimandrew/multi-server
  - docker push klimandrew/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-docker
  env: MultiDocker-env
  bucket_name: 'elasticbeanstalk-us-east-2-560109813412'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
